version: '3.8'
services:
  nginx:
    image: nginx:1.21.6
    ports:
      - 8080:80
    container_name: videos_nginx
    restart: always
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/application
    depends_on:
      - php
    links:
      - php
    env_file:
      - .env
  php:
    build:
      context: ./docker/php
    container_name: videos_php
    volumes:
      - ./:/var/www/application
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:14.2
    container_name: videos_postgres
    volumes:
      - pg:${POSTGRES_PGDATA}
    ports:
      - 6543:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      PGDATA: ${POSTGRES_PGDATA}
volumes:
  pg: